version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_PORT=${PGPORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql