version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_PORT=${PGPORT}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    volumes:
      - './web-app:/app'
      - '/app/node_modules'
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  express-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    restart: on-failure
    container_name: express-api
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - ./server:/app # Look at the server directory and copy everything into the app folder in the container
    environment:
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}